### ISSUE TITLE
Bouncing between "authorize", "callback" and "/", ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by IchSchreiGleich** [lukaszraczylo/traefikoidc#12]
I am using this plugin in treafik in conjunktion with auth0 and have configured it with
```
traefikoidc:
  callbackURL: /callback
  clientID: PLACEHOLDER
  clientSecret: PLACEHOLDER
  excludedURLs:
	- /login
  forceHTTPS: false
  logLevel: debug
  logoutURL: /logout
  providerURL: https://PLACEHOLDER.eu.auth0.com
  rateLimit: 100
  scopes:
	- openid
	- email
	- profile
  sessionEncryptionKey: PLACEHOLDER 
```
The first attempt is successful, I am redirected, use my Passkey and return to my origin and am authenticated.

Now I logout with
```
https://PLACEHOLDER.eu.auth0.com/v2/logout?client_id=PLACEHOLDER&returnTo=https://www.PLACEHOLDER.com/logout
```
and it seem to log me out, because the text "Logged out" is shown.

But when I try to sign in again (accessing https://www.PLACEHOLDER.com with redirection to auth0), I can use my Passkey but then nothing happens. Instead, the browser reports: ERR_TOO_MANY_REDIRECTS

The strange thing is that after successfully logging out and restarting traefik, the whole thing works fine. But only exactly once. Until the next time traefik is restarted.

I suspect that some status of the plugin is not cleaned up when logging out and therefore the whole thing fails?
