### ISSUE TITLE
Possible bug when having multiple middlewares

### ISSUE THREAD

**Issue by mofr93** [lukaszraczylo/traefikoidc#16]
I have two middlewares

1. traefikoidc-default (uses Vault as OIDC provider)
2. traefikoidc-azuread (azure OIDC)

The problem is when I use the second `traefikoidc-azuread` middleware i get redirected to the `providerUrl` configured in `traefikoidc-default`.

Restarting Traefik sometimes fixes the issue for a short time. It might have something to do with the order in which the middleware is loaded.

`traefikoidc-default`
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: traefik:traefik.io/Middleware:addon-traefik/traefikoidc-default
  name: traefikoidc-default
  namespace: addon-traefik
spec:
  plugin:
    traefikoidc:
      allowedUserDomains:
        - company.dk
      callbackUrl: /oidc/callback
      clientId: urn:k8s:secret:traefikoidc:CLIENT_ID
      clientSecret: urn:k8s:secret:traefikoidc:CLIENT_SECRET
      excludedURLs:
        - /monitor/alive
        - /healthz
      forceHTTPS: true
      logLevel: info
      logoutURL: /oidc/logout
      providerUrl: urn:k8s:secret:traefikoidc:ISSUER
      rateLimit: 1000
      scopes:
        - openid
        - profile
        - dev-vsphere-denver-traefik-default-scope-user
        - dev-vsphere-denver-traefik-default-scope-groups
      sessionEncryptionKey: somekey
```

`traefikoidc-azuread`
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: traefik:traefik.io/Middleware:addon-traefik/traefikoidc-azuread
  name: traefikoidc-azuread
  namespace: addon-traefik
spec:
  plugin:
    traefikoidc:
      allowedUserDomains:
        - company.dk
      callbackUrl: /oidc/callback
      clientId: urn:k8s:secret:traefikoidc-azuread:CLIENT_ID
      clientSecret: urn:k8s:secret:traefikoidc-azuread:CLIENT_SECRET
      excludedURLs:
        - /monitor/alive
        - /healthz
      forceHTTPS: true
      logLevel: info
      logoutURL: /oidc/logout
      providerUrl: urn:k8s:secret:traefikoidc-azuread:ISSUER
      rateLimit: 1000
      scopes:
        - openid
        - profile
        - email
      sessionEncryptionKey: somekey
```

**Comment by lukaszraczylo** [comment]
I have similar setup in my test environment:

```
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: raczylo-oidc
  namespace: traefik
spec:
  plugin:
    traefikoidc:
      providerURL: urn:k8s:secret:traefik-middleware-oidc:ISSUER
      clientID: urn:k8s:secret:traefik-middleware-oidc:CLIENT_ID
      clientSecret: urn:k8s:secret:traefik-middleware-oidc:SECRET
      sessionEncryptionKey: xxx
      callbackURL: /oidc2/callback
      logoutURL: /oidc2/logout
      rateLimit: 500
      scopes:
        - openid
        - email
        - profile
        - roles
      forceHTTPS: true
      excludedURLs:
        - /fonts
        - /images
        - /public
        - /assets
        - /_next/static
        - /api/datasources/proxy/uid/vmetrics-ds/api/v1/query_range
      allowedRolesAndGroups:
        - admin-endpoints
```

and 

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: raczylo-oidc-guest
  namespace: traefik
spec:
  plugin:
    traefikoidc:
      providerURL: urn:k8s:secret:traefik-middleware-oidc-guest:ISSUER
      clientID: urn:k8s:secret:traefik-middleware-oidc-guest:CLIENT_ID
      clientSecret: urn:k8s:secret:traefik-middleware-oidc-guest:SECRET
      sessionEncryptionKey: yyy
      callbackURL: /oidc2/callback
      logoutURL: /oidc2/logout
      scopes:
        - openid
        - email
        - profile
        - roles
      forceHTTPS: true
      excludedURLs:
        - /fonts
        - /images
        - /public
        - /assets
        - /_next/static
        - /files
      allowedRolesAndGroups:
        - guest-endpoints
```

This configuration is stable and works fine. There could be a chance the issue depends on the virtual host configuration ( for example IngressRoute ) and any redirects you may have on the way.

Could you check the target URL with the `curl -vvv` and see if it goes through some additional redirections which could possibly trigger the other middleware to respond?

**Comment by mofr93** [comment]
The ingressRoute I'm testing only contain the traefikoidc middleware.
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: traefik:traefik.io/IngressRoute:addon-traefik/traefik-dashboard-https
  name: traefik-dashboard-https
  namespace: addon-traefik
spec:
  entryPoints:
    - websecureint
  routes:
    - kind: Rule
      match: Host(`traefik-dev-vsphere-denver.dsservice.lokal`)
      middlewares:
        - name: traefikoidc-default
      services:
        - kind: TraefikService
          name: api@internal
  tls:
    domains:
      - main: traefik-dev-vsphere-denver.dsservice.lokal
```

We have 3 replicas of Traefik on our cluster. They seem to report different location depending on which one i hit.

```
curl --insecure -vvv https://traefik-dev-vsphere-denver.dsservice.lokal
*   Trying 192.168.170.29:443...
* Connected to traefik-dev-vsphere-denver.dsservice.lokal (192.168.170.29) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.dsservice.lokal
*  start date: Oct 12 10:59:58 2022 GMT
*  expire date: Aug 11 09:01:16 2027 GMT
*  issuer: DC=lokal; DC=danskespil; CN=Danske Spil Issuing CA 01
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://traefik-dev-vsphere-denver.dsservice.lokal/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: traefik-dev-vsphere-denver.dsservice.lokal]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: traefik-dev-vsphere-denver.dsservice.lokal
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/2 302 
< location: https://vault-nonprod-private-vault-[REDACTED].z1.hashicorp.cloud:8200/ui/vault/admin/ds-root/identity/oidc/provider/dev-vsphere-denver-traefik-default-provider/authorize?[REDACTED]
< set-cookie: _raczylo_oidc=[REDACTED]=; Path=/; Expires=Thu, 12 Dec 2024 11:12:11 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Lax
< set-cookie: _raczylo_oidc_access=[REDACTED]; Path=/; Expires=Thu, 12 Dec 2024 11:12:11 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Lax
< set-cookie: _raczylo_oidc_refresh=[REDACTED]; Path=/; Expires=Thu, 12 Dec 2024 11:12:11 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Lax
< content-length: 0
< date: Wed, 11 Dec 2024 11:12:11 GMT
< 
* Connection #0 to host traefik-dev-vsphere-denver.dsservice.lokal left intact
```

And a second try:
```
*   Trying 192.168.170.29:443...
* Connected to traefik-dev-vsphere-denver.dsservice.lokal (192.168.170.29) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.dsservice.lokal
*  start date: Oct 12 10:59:58 2022 GMT
*  expire date: Aug 11 09:01:16 2027 GMT
*  issuer: DC=lokal; DC=danskespil; CN=Danske Spil Issuing CA 01
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://traefik-dev-vsphere-denver.dsservice.lokal/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: traefik-dev-vsphere-denver.dsservice.lokal]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: traefik-dev-vsphere-denver.dsservice.lokal
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/2 302 
< location: https://login.microsoftonline.com/[REDACTED]/oauth2/v2.0/authorize?[REDACTED]
< set-cookie: _raczylo_oidc=[REDACTED]; Path=/; Expires=Thu, 12 Dec 2024 11:13:34 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Lax
< set-cookie: _raczylo_oidc_access=[REDACTED]; Path=/; Expires=Thu, 12 Dec 2024 11:13:34 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Lax
< set-cookie: _raczylo_oidc_refresh=[REDACTED]; Path=/; Expires=Thu, 12 Dec 2024 11:13:34 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=Lax
< content-length: 0
< date: Wed, 11 Dec 2024 11:13:34 GMT
< 
* Connection #0 to host traefik-dev-vsphere-denver.dsservice.lokal left intact
```

So it appears that the the location keeps jumping back and fourth between the two providers.
