### ISSUE TITLE
About sending headers downstream

### ISSUE THREAD

**Issue by ovizii** [lukaszraczylo/traefikoidc#32]
I am trying to log into calibre-web via headers passed downstream: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy 

It expects the username. 

Your docs state this (see below). 
Could you please double-check these are correct especially these:` X-Forwarded-User` and `X-Auth-Request-User` as they seem to be identical in their description? 
Also, can we have another header for `scope: profile` `claim: preferred_username` and maybe `claim: name` Possibly `scope: openid claim: sub `as I am not exactly sure what calibre-web is expecting.

> Headers Set for Downstream Services
> When a user is authenticated, the middleware sets the following headers for downstream services:
> 
> X-Forwarded-User: The user's email address
> X-User-Groups: Comma-separated list of user groups (if available)
> X-User-Roles: Comma-separated list of user roles (if available)
> X-Auth-Request-Redirect: The original request URI
> X-Auth-Request-User: The user's email address
> X-Auth-Request-Token: The user's access token

**Comment by ovizii** [comment]
Btw. looking at another oidc traefik plugin I see they even have the luxury of customizing these headers like this. Just a suggestion for future features :-)


```
          Headers:
            - Name: "X-FORWARDED-EMAIL"
              Value: "{{`{{ .claims.email }}`}}"
            - Name: "X-FORWARDED-USER"
              Value: "{{`{{ .claims.preferred_username }}`}}"
            - Name: "Authorization"
              Value: "{{`Bearer {{ .accessToken }}`}}"
```
