### ISSUE TITLE
Scopes appended instead of replaced

### ISSUE THREAD

**Issue by ricristian** [lukaszraczylo/traefikoidc#51]
Hi, 

I've tried latest version v0.6.1 for oidc implementation ( actually the is the only one ) 

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
  namespace: monitoring
spec:
  plugin:
    traefik-oidc-auth:
      providerURL: https://auth.keycloack.com/realms/master
      clientId: "test"
      clientSecret: "xxxx"
      sessionEncryptionKey: "xxxxxxxxxxxxxxxxx"
      callbackURL: "/oauth2/callback"
      scopes: [ "email" ]
      allowedUsers: "test"
      logLevel: debug
```

And in Traefik logs I keep see

`
DEBUG: TraefikOidcPlugin: 2025/06/01 01:26:06 Redirecting user to OIDC provider: https://auth.keycloak.com/realms/master/protocol/openid-connect/auth?client_id=test&nonce=cnUSbgi-LBJTw213DdZZ39MZjLHP75Zl1htI%3D&redirect_uri=ws%3A%2F%2Fmydomain.test.io%2Foauth2%2Fcallback&response_type=code&scope=email+profile+email+offline_access&state=xas221-xx212-44dd-8a14-4e8ebf02549a
`

For some reason instead of having only one scope  email, somehow my scope was appended at the begging of +profile+email+offline_access which is kinda bad because not all the idp's will allow all scopes, some of them will allow only one scope

Any idea how can this behaviour can be avoided or is something desired ? 
Thank you

**Comment by lukaszraczylo** [comment]
Ahh I see 😅 Well, my bad - most likely I'll add extra flag to prevent the merge and overwrite in that case to preserve the backward compatibility

**Comment by ricristian** [comment]
That would be fantastic, please let me know when you add such flag so I can test and provide more feedback about it. 
Thanks a lot man for your effort

**Comment by lukaszraczylo** [comment]
Alrighty - so new flag added in `v0.6.2-beta6`.
If you set `overrideScopes` to true the middleware will use only scopes you have provided

**Comment by lukaszraczylo** [comment]
My bad - I completely forgotten that traefik uses outdated yaegi interpreter which does not like the newer golang syntax ( since generics were introduced ). I spent most of the day hunting down things - https://github.com/lukaszraczylo/traefikoidc/pull/54/commits/667b4213fe2fdc9eb0833594bf58c2fe39cec0f6 

Now it comes up fine in v0.6.2-beta7

**Comment by ricristian** [comment]
You're not going to like this but 

```Authentication error from provider: Invalid scopes: openid profile email offline_access``` 

After I saw that I was thinking ok maybe is something on my cache. 

I've added a new scope called test3 just for the sake of testing 

```
    traefik-oidc-auth:
      providerURL: https://<endpoint>/realms/syncron
      clientId: "xxx"
      clientSecret: "xxxxx"
      sessionEncryptionKey: "xxxxxx"
      callbackURL: "/oauth2/callback"
      scopes: [ "email" , "test3"]
      allowedUsers: "cristian"
      logLevel: info
      overrideScopes: true
```

<img width="775" alt="Image" src="https://github.com/user-attachments/assets/a8c2b00c-db84-4e57-a383-c833fb4e3398" />

**Comment by ricristian** [comment]
Ohh well don't be so sure another weird thing: 

`scopes: [ "email", "test3" ]` -> Authentication error from provider: Invalid scopes: email test3 fantastic 

`scopes: [ "email" ]` -> Authentication error from provider: Invalid scopes: email profile -> wrong profile shouldn't be here since I have overrideScopes: true

**Comment by ricristian** [comment]
P.S: I've just tested https://github.com/sevensolutions/traefik-oidc-auth latest version v0.12.0

```
    traefik-oidc-auth:
      Secret: "xxxxxx"
      Provider:
        Url: "https://xxxxx/realms/syncron"
        ClientId: "test"
        ClientSecret: "xxxxx"
        ValidAudience: "account"
      Scopes: [ "email" ]
```

I had to add `ValidAudience: "account"` and it worked out of the box.  While I've switched my stuff towards to the mentioned plugin I've kept a route for this plugin if you're willing keep testing together I'm down to keep continuing tests with you. Multiple functional oidc plugins doesn't hurt the community when greed comes in to play :)
