### ISSUE TITLE
Azure OIDC not working in v0.6.1

### ISSUE THREAD

**Issue by mofr93** [lukaszraczylo/traefikoidc#53]
Hi,

Upgraded from v0.5.34

### Environment
Plugin Version: v0.6.1
Traefik Version: v35.2.0
OIDC Provider: Azure
OS: MacOS

### Expected Behavior
Login flow working as in v0.5.34

### Actual Behavior
I get a redirection loop and sometimes "CSRF token missing in session"
Tried clearing cookies with no luck.

### Logs
error in log:
`
Access token validation failed: signature verification failed: crypto/rsa: verification error
`

## Middleware config

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefikoidc-azuread
spec:
  plugin:
    traefikoidc:
      clientId: XXX
      clientSecret: XXX
      providerUrl: XXX
      callbackUrl: /oidc/callback
      logoutURL: /oidc/logout
      scopes:
        - openid
        - profile
        - email
      allowedUserDomains:
        - exampledomain.com
      excludedURLs:
        - /monitor/alive
        - /healthz
      logLevel: debug
      forceHTTPS: true
      rateLimit: 1000 
      sessionEncryptionKey: XXX
```
