### ISSUE TITLE
Templated Headers not working in v0.6.2-beta4

### ISSUE THREAD

**Issue by SaveRobots** [lukaszraczylo/traefikoidc#55]
In latest beta, trying to forward claims using the templated headers feature. For example, with the following dynamic config:

```
oidc:
  plugin:
    oidc:
      clientID: {REDACTED}
      clientSecret: {REDACTED}
      providerURL: {REDACTED}
      sessionEncryptionKey: {REDACTED}
      scopes:
        - "openid"
        - "profile"
        - "email"
      headers:
        - name: "Authorization"
          value: "Bearer {{.AccessToken}}"
      callbackURL: /oauth2/callback
      logoutURL: /oauth2/logout
      logLevel: debug
```

We get the following error in Traefik logs upon start of the container or application of the config:

```
2025-06-19T16:06:07Z ERR [github.com/traefik/traefik/v3/pkg/provider/file/file.go:105](http://github.com/traefik/traefik/v3/pkg/provider/file/file.go:105) > Error while building configuration (for the first time) error="/etc/traefik/dynamic_conf.yml: template: :37:31: executing \"\" at <.AccessToken>: can't evaluate field AccessToken in type bool" providerName=file
```

We see the same error when trying to use any claim we know to exist in the token, such as "{{.Claims.name}}". This error causes the router applied to return 404 error. However, when removing templating from the value completely and only forwarding static text, the header forwaring does appear to work. Please advise, thank you.
